WeatherApplication/Models/CityWeather.cs
namespace WeatherApplication.Models
{
    public class CityWeather
    {
        public string CityUniqueCode { get; set; }
        public string CityName { get; set; }
        public DateTime DateAndTime { get; set; }

        public int TemperatureFahrenheit { get; set; }
    }
}

WeatherApplication/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherApplication.CityWeatherRepository;
using WeatherApplication.Models;

namespace WeatherApplication.Controllers
{
    [Controller]
    public class WeatherController : Controller
    {
        private readonly IRepository _repository;

        public WeatherController(IRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        [Route("/")]
        public IActionResult Index()
        {
            IList<CityWeather> cities = _repository.GetAllEntities();

            if (cities is null || cities.Count == 0)
            {
                ViewBag.Title = "Not Found | 404";
                return View("Not_Found");
            }
            ViewBag.Title = "All Cities";
            return View(cities);
        }

        [HttpGet]
        [Route("weather/{cityCode}")]
        public IActionResult Details(string cityCode)
        {
            CityWeather? cityWeather = _repository.GetByCode(cityCode);

            if(cityWeather == null)
            {
                ViewBag.Title = "Not Found | 404";
                return View("Not_Found");
            }
            ViewBag.Title = $"{cityWeather.CityName} Details";
            return View(cityWeather);
        }

    }
}

WeatherApplication/ViewComponents/NavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WeatherApplication.ViewComponents
{
    [ViewComponent]
    public class NavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string name)
        {
            return View(model:name);
        }
    }
}

WeatherApplication/Views/Shared/Components/Nav/Default.cshtml
@model string


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="/">@Model</a>

    </div>
</nav>

WeatherApplication/Views/Shared/Not_Found.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/notfoundstyles.css" rel="stylesheet" />
</head>
<body>
    <!-- Not Found Page HTML -->
    <div class="page-not-found pt-5">
        <div class="bg-light shadow">
            <h2>4<i class="bi bi-bug"></i>4</h2>
            <h3 class="mt-4">Opps! Page Not Found</h3>
            <div class="mt-5">
                <button type="button" class="btn m-2 m-md-0 btn-primary" href="/"><i class="bi bi-house-door-fill"></i> Back Home</button>
            </div>
        </div>
    </div>
</body>
</html>

WeatherApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    @await Component.InvokeAsync("Nav", new {name="Weather App"});
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Demo WeatherApp</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

WeatherApplication/Views/Shared/_PartialView.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="/">WeatherApp</a>

    </div>
</nav>

WeatherApplication/Views/Weather/Details.cshtml
@using System.Collections.Generic

@model CityWeather
        
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                        <h2 class="card-title">@Model.CityName - @Model.CityUniqueCode</h2>
                        <p class="card-text">@Model.DateAndTime.TimeOfDay | @Model.TemperatureFahrenheit Fahrenheit</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="/">Return to List</a></div>
                    </div>
                </div>

            </div>
    

WeatherApplication/Views/Weather/Index.cshtml
@using System.Collections.Generic

@model IList<CityWeather>

        @foreach(CityWeather cityWeather in Model){
        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">@cityWeather.CityName - @cityWeather.CityUniqueCode</h2>
                        <p class="card-text">@cityWeather.DateAndTime.TimeOfDay | @cityWeather.TemperatureFahrenheit Fahrenheit</p>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="/weather/@cityWeather.CityUniqueCode">More Info</a></div>
                </div>
            </div>
            
        </div>}
    